### ISSUE TITLE
cubicDot function error in math_type_define.h

### ISSUE THREAD

**Issue by DaegyuLim** [saga0619/dyros_tocabi#1]
code should be changed as below

  if (time < time_0)
  {
    x_t = x_dot_0;
  }
  else if (time > time_f)
  {
    x_t = x_dot_f;
  }

instead of 

  if (time < time_0)
  {
    x_t = x_0;
  }
  else if (time > time_f)
  {
    x_t = x_f;
  }

**Comment by kdh0429** [comment]
Issue has been reflected.
