### ISSUE TITLE
tc.mode and atc.mode should be seperated

### ISSUE THREAD

**Issue by DaegyuLim** [saga0619/dyros_tocabi#10]
when tc.mode is activated, act.mode==0 is also working because act.mode is set zero initially.
In the same way, when the arm control mode is on, tc.mode==0 (pelv control) is running simultaneously.

**Comment by Junhyung-Kim** [comment]
You can solve the problem.
if(tc.mode == 0 && arm control mode is off)
{
   //pelvis control
}

When I command walking to robot simulation, I already have same isssues.
I solve the issues.
if(tc.mode == 0 && tc.walking_enable == 0)
{
   //pelvis control
}
else if(tc.mode == 0 && tc.walking_enable == 1)
{
  //walking
}

**Comment by saga0619** [comment]
arm command and task command are integrated.
