### ISSUE TITLE
task_control_torque_QP2 error in wholebody_controller.cpp

### ISSUE THREAD

**Issue by DaegyuLim** [saga0619/dyros_tocabi#16]
When i use single support foot(wc_.set_contact(tocabi_, 1, 0)), task_control_torque_QP2 give me eigen matrix size error. 
The error is because of the line 742 and below:

   MatrixXd W_fr;

    W_fr.setZero(6, 12);
    W_fr.block(0, 0, 3, 3) = Robot.link_[Left_Foot].Rotm;
    W_fr.block(3, 3, 3, 3) = Robot.link_[Left_Foot].Rotm;
    W_fr.block(3, 0, 3, 3) = Robot.link_[Left_Foot].Rotm * DyrosMath::skm(Robot.link_[Left_Foot].xpos_contact - Robot.com_.pos);

    W_fr.block(0, 6, 3, 3) = Robot.link_[Right_Foot].Rotm;
    W_fr.block(3, 9, 3, 3) = Robot.link_[Right_Foot].Rotm;
    W_fr.block(3, 6, 3, 3) = Robot.link_[Right_Foot].Rotm * DyrosMath::skm(Robot.link_[Right_Foot].xpos_contact - Robot.com_.pos);

    VectorXd fr = W_fr * fc;
    Vector3d r_zmp = GetZMPpos(Robot, fc);
    qpt_info = false;
    if (qpt_info)
    {
        std::cout << "##########################" << std::endl;
        std::cout << "contact info ! " << std::endl
                  //<< "fc result : " << std::endl
                  //<< fc << std::endl
                  //<< "fc local : " << std::endl
                  //<< Robot.link_[Left_Foot].Rotm.transpose() * fc.segment(0, 3) << std::endl
                  //<< Robot.link_[Left_Foot].Rotm.transpose() * fc.segment(3, 3) << std::endl
                  //<< Robot.link_[Right_Foot].Rotm.transpose() * fc.segment(6, 3) << std::endl
                  //<< Robot.link_[Right_Foot].Rotm.transpose() * fc.segment(9, 3) << std::endl
                  //<< "qp fz : " << fc(2) + fc(8) << std::endl
                  //<< " fstar*lambda = " << (Robot.lambda * qpres.segment(MODEL_DOF + contact_dof, task_dof))(2) << std::endl
                  //<< " qp + lambda f* : " << (Robot.lambda * qpres.segment(MODEL_DOF + contact_dof, task_dof))(2) + fc(2) + fc(8) << std::endl
                  //<< " fstar desired : " << std::endl
                  //<< f_star_ << std::endl
                  //<< "fstar qp : " << std::endl
                  //<< qpres.segment(MODEL_DOF + contact_dof, task_dof) << std::endl
                  << "ft fz : " << Robot.ContactForce_FT(2) + Robot.ContactForce_FT(8) << std::endl
                  << "resultant fz : " << std::endl
                  << fr << std::endl
                  << "resultant zmp x : " << r_zmp(0) << "\t y : " << r_zmp(1) << std::endl
                  << "estimate zmp x : " << zmp_com_e_x << "\t y : " << zmp_com_e_y << std::endl
                  << "com pos x : " << Robot.com_.pos(0) << "\t y : " << Robot.com_.pos(1) << std::endl
                  << "zmp result : " << std::endl
                  << "Left foot  x :" << fc(4) / fc(2) << "\t y :" << fc(3) / fc(2) << std::endl
                  << "Right foot x :" << fc(10) / fc(8) << "\t y :" << fc(9) / fc(8) << std::endl

                  << "fstar com induced : " << std::endl
                  << fstar_com << std::endl
                  << "fstar from torque : " << std::endl
                  << J_com * Robot.A_matrix_inverse * Robot.N_C * (Robot.Slc_k_T * task_torque - Robot.G) << std::endl;
    }

    fc.segment(0, 3) = Robot.link_[Left_Foot].Rotm.transpose() * fc.segment(0, 3);
    fc.segment(3, 3) = Robot.link_[Left_Foot].Rotm.transpose() * fc.segment(3, 3);
    fc.segment(6, 3) = Robot.link_[Right_Foot].Rotm.transpose() * fc.segment(6, 3);
    fc.segment(9, 3) = Robot.link_[Right_Foot].Rotm.transpose() * fc.segment(9, 3);

    double ft_zmp_l = Robot.ContactForce_FT(3) / Robot.ContactForce_FT(2);
    double ft_zmp_r = Robot.ContactForce_FT(9) / Robot.ContactForce_FT(8);

    if (abs(ft_zmp_l) > 0.04)
    {
        //std::cout << "lf zmp over limit : " << ft_zmp_l << std::endl;
    }
    if (abs(ft_zmp_r) > 0.04)
    {
        //std::cout << "rf zmp over limit : " << ft_zmp_r << std::endl;
    }

    Robot.ContactForce = fc;

"W_fr" should be resized by 6xcontact_dof and fc.segment should be treated depending on the contact num

Anyway, algorithm has no error.

**Comment by saga0619** [comment]
fixed
